### ISSUE TITLE
Empty bill object on specific member vote positions list when it's not on a bill

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#148]
This may have been intended, but just noticed an empty `bill` object when the vote isn't on a bill:

```json
                  {
           "member_id": "R000487",
           "chamber": "House",
           "congress": "115",
           "session": "1",
           "roll_call": "392",
           "vote_uri": "https://api.propublica.org/congress/v1/115/house/session
s/1/votes/392.json",
           "bill": {
           },
           "description": "",
           "question": "Table Appeal of the Ruling of the Chair",
           "result": "Passed",
           "date": "2017-07-19",
           "time": "14:01:00",
```

I had based my client logic in determining whether a vote was on a bill by the presence of the `bill` field, but can move it to lean on the presence of the `bill_id` sub-field if need be. Whichever works, as long as it's consistent.

**Comment by dwillis** [comment]
It is intended, but not just to make my life easier. There are some votes that occur on bills for which we have little or no information on (they were introduced the day they were voted on). We've fixed it now so that when a bill record does not exist in the database but a vote occurs on that bill, we'll provide a bill object and the `bill_id` and `number` attributes. That will be live tonight.
