### ISSUE TITLE
Sunlight API merger: Member responses

### ISSUE THREAD

**Issue by dwillis** [propublica/congress-api-docs#7]
[Sunlight's legislator responses](https://propublica.github.io/congress/legislators.html) have a number of fields that we aim to include in the ProPublica API. The plan is to use the existing ProPublica Congress API [member responses](https://propublica.github.io/congress-api-docs/#members) and add Sunlight response data and functionality to them.

The following Sunlight fields will NOT be included in the merged API:

* `thomas_id` - Thomas no longer exists.
* `oc_email` - OpenCongress no longer exists

The following Sunlight fields will be added in member responses:

* `ocd_id` - Open Civic Division identifier
* `office` - the DC office
* `phone` - the DC office phone number
* `in_office` - boolean for whether member is a current lawmaker
* `crp_id` - Center for Responsive Politics identifier
* `senate_class` - class of Senator
* `state_rank ` - for senators, their in-state rank (junior or senior)
* `title` - Sen, Rep
* `chamber` - house or senate
* `leadership_role` - if a lawmaker holds a leadership position
* `lis_id` - for senators, legislative information system identifier
* `contact_form` - URL of official site contact form
* `votesmart_id` - VoteSmart.org identifier
 
We will *not* be supporting [Sunlight's legislator `locate` response](https://propublica.github.io/congress/legislators.html#legislatorslocate), but are encouraging users to move to the [Google Civic API](https://developers.google.com/civic-information/).

We will not be supporting the filtering syntax that Sunlight uses for its responses. Some of the same functionality is available in current ProPublica responses; if there are specific filters that users feel strongly about that we do not support we'll consider adding them.

**Comment by noslouch** [comment]
Hey, what's the status on this? @nypublicradio is interested in using the legislator locate API. I was trying to demo it today and received 400 responses against the sunlight foundation's domain. Anything we can do to help?

**Comment by dwillis** [comment]
@noslouch we've been discussing this and we are going to be encouraging folks to use the Google Civic API instead and won't be offering a location-based lookup in the ProPublica Congress API. We already use Google for our Represent app and feel it is well-suited to the task. Maintaining a duplicate service didn't make sense to us.

**Comment by noslouch** [comment]
woah! who knew about this! thanks for the tip. looking into it now.

**Comment by dwillis** [comment]
These changes have been made in the API, see examples [here](https://propublica.github.io/congress-api-docs/#members).

**Comment by stevengharris** [comment]
I notice "chamber" is still missing [here](https://propublica.github.io/congress-api-docs/#members) and that "office" is there but empty (it's filled-in on SunlightLabs). Would it also be possible to include "fax", "contact_form", and "youtube_account"? Fax (as retro as it is) is sometimes suggested as the best vehicle, and a lot of the reps use a contact form for more routine interactions.

**Comment by dwillis** [comment]
@stevengharris `chamber` is available on both [list of members](https://propublica.github.io/congress-api-docs/#lists-of-members) responses and on get specific member responses (within the `roles` attribute). We'll add `fax`, `contact_form` and `youtube_account`, although the last one is already available in specific member responses.

**Comment by dwillis** [comment]
@stevengharris We've added `fax`, `contact_form` and `youtube_account` to member responses (both lists and specific member).

**Comment by stevengharris** [comment]
I was using the SunlightLabs votes filter to return the result for a vote, so I can display it next to the member recent votes. Here's a curl equivalent example:

curl "https://congress.api.sunlightfoundation.com/votes?chamber=senate&number=51&year=2017&fields=result"

Without the filter on result, I have to retrieve all members votes, etc using (the curl equivalent):

curl "https://api.propublica.org/congress/v1115/senate/sessions/1/votes/51.json" -H "X-API-Key:<API_KEY>"

and then parse it to find the one line "result". This works, but is pretty heavyweight in comparison. I wondered if a simpler alternative to the filter would just be to include a "result" field in the ProPublica member votes response. For example (since I'm displaying for a particular member), if there was a "result" field (like "position") in each "votes" entry for the following, it would eliminate my call for the result completely:

curl "https://api.propublica.org/congress/v1/members/F000062/votes.json" -H "X-API-Key:<API_KEY>"

Thanks very much for including the fields I asked for earlier! Works great.

**Comment by dwillis** [comment]
@stevengharris that seems like a pretty reasonable request. We might include 3-4 other fields from the `Vote` object as well.

**Comment by dwillis** [comment]
@stevengharris we've added `result` and a few other attributes to the Member Votes response and will be updating the examples in the docs soon. Let me know if you think this works for you.

**Comment by stevengharris** [comment]
Works great and eliminated lots of API calls from my app. Thank you!
